opt_in_rules:
    - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - EmployeeRosterTests/GeneratedMocks.swift
    - EmployeeRosterUITests/

line_length:
  - 300 # warning
  - 400 # error

function_body_length:
  - 300 # warning
  - 400 # error

type_body_length:
  - 300 # warning
  - 400 # error
    
opt_in_rules:
  - empty_count

custom_rules:
    rule_id:
        included: Source/SwiftLintFramework/Rules/.+/\w+\.swift
        name: Rule ID
        message: Rule IDs must be all lowercase, snake case and not end with `rule`
        regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
        severity: error
    fatal_error:
        name: Fatal Error
        excluded: "Tests/*"
        message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
        regex: \bfatalError\b
        match_kinds:
          - identifier
        severity: error
    rule_test_function:
        included: Tests/SwiftLintFrameworkTests/RulesTests.swift
        name: Rule Test Function
        message: Rule Test Function mustn't end with `rule`
        regex: func\s*test\w+(r|R)ule\(\)
        severity: error
  
# Rules to encourage usage of SwiftGen
custom_rules:
    swiftgen_assets:
        name: "SwiftGen Assets"
        regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
        message: "Use Asset.<asset> instead"
        severity: error
    swiftgen_colors:
        name: "SwiftGen Colors"
        regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
        message: "Use ColorName.<color> instead"
        severity: error
    swiftgen_fonts:
        name: "SwiftGen Fonts"
        regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
        message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
        severity: error
    swiftgen_storyboards:
        name: "SwiftGen Storyboards"
        regex: '(UIStoryboard\(name: ?"?.+"?, ?bundle:.+\))|(instantiateViewController\(withIdentifier:.+?\))|(instantiateInitialViewController\(\))'
        message: "Use StoryboardScene.<storyboad>.<scene>.instantiate() instead"
        severity: error
    swiftgen_storyboard_segue_perform:
        name: "SwiftGen Storyboard Segue Identifier"
        regex: 'performSegue\(withIdentifier: ?"?.+"?, ?sender:.+\)'
        message: "Use perform(segue: StoryboardSegue.<storyboard>.<segue>, sender: <sender>) instead"
        severity: error
    swiftgen_storyboard_segue_prepare:
        name: "SwiftGen Storyboard Segue Prepare"
        regex: 'segue.identifier'
        message: "Use StoryboardSegue.<storyboard>(segue) instead"
        severity: error
    swiftgen_strings:
        name: "SwiftGen Strings"
        regex: 'NSLocalizedString'
        message: "Use L10n.key instead"
        severity: error
